openapi: 3.0.3

info:
  title: Todo API
  description: An API for creating and managing tasks
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: DEV (local)

paths:
  /info:
    get:
      summary: Returns information about this API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
              example:
                version: "80fce9d-20201115"

  /todo:
    post:
      summary: Create a new task
      description: >
        Creates a new persistent task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTodoRequest"
            example:
              category: shopping
              text: Don't forget the milk
              status: TODO
              tags:
                - groceries
                - food
      responses:
        "200":
          description: Successfully created task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
              example:
                id: -MMJam1XPAFVTTajrZYB
                rev: -MMJam1XPAFVTTajrZYC
                category: shopping
                text: Don't forget the milk
                status: TODO
                tags:
                  - groceries
                  - food
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestResponse"
              example:
                message: Validation failed
                details:
                  - "Key: 'CreateTodoRequest.Tags' Error:Field validation for 'Tags' failed on the 'required' tag"

components:
  schemas:
    InfoResponse:
      type: object
      required: [version]
      properties:
        version:
          type: string

    CreateTodoRequest:
      type: object
      required: [category, text, status, tags]
      properties:
        category:
          type: string
        text:
          type: string
        status:
          type: string
        tags:
          type: array
          items:
            type: string

    Todo:
      type: object
      required: [id, rev, category, text, status, tags]
      properties:
        id:
          type: string
        rev:
          type: string
        category:
          type: string
        text:
          type: string
        status:
          type: string
        tags:
          type: array
          items:
            type: string

    BadRequestResponse:
      type: object
      required: [message, details]
      properties:
        message:
          type: string
        details:
          type: array
          items:
            type: string
