name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        working-directory: pact/client
        run: ./gradlew clean check
  
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Install Pact Tools
        run: |
          mkdir -p $GITHUB_WORKSPACE/pact-cli
          cd $GITHUB_WORKSPACE/pact-cli
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.89.01-rc1/pact-1.89.01-rc1-linux-x86_64.tar.gz
          tar xzf pact-1.89.01-rc1-linux-x86_64.tar.gz
          echo "$GITHUB_WORKSPACE/pact-cli/pact/bin" >> $GITHUB_PATH
          go install github.com/pact-foundation/pact-go@v1
      - name: Run go test
        run: |
          cd pact/server
          go test -v
